apiVersion: v1
kind: Secret
metadata:
  name: {{ template "insight.fullname" . }}-applicationyaml
  labels:
    app: {{ template "insight.name" . }}
    chart: {{ template "insight-server.chart" . }}
    component: {{ .Values.insightServer.name }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
type: Opaque
stringData:
  application.yaml: |
{{ toYaml .Values.applicationConfigs | indent 4 }}
